/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package firstGradleProject;
import static spark.Spark.*;

public class App {
    public static void main(String[] args) {
       get("/users/0/welcome", (req,res) -> {return "Hallo Welt!";});
    }
    public String getGreeting() {
        return "Hallo Welt";
    }
}
